#######################################################################
# Define the build environments
#######################################################################

language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

arch:
    - amd64
    - arm64

# On OSX, 'gcc' is an alias for 'clang' anyway, and finding/installing
# a gcc would be a bit of extra work with uncertain benefits. So on
# OSX, we only do the 'clang' builds.
jobs:
  exclude:
  - os: osx
    compiler: gcc

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty

#######################################################################
# The actual scripts to execute within the respective build jobs
#######################################################################

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install e2fsprogs; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y e2fslibs-dev uuid-dev ss-dev; fi

before_script:
    - autoreconf -vis

script: sh .travis-script.sh
